name: Get node version from package.json

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: install
        run: yarn install

      - name: lint
        run: yarn lint
